/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FloatContainer: typeof import('./src/components/FloatContainer.vue')['default']
    FloatProxy: typeof import('./src/components/FloatProxy.vue')['default']
    Init: typeof import('./src/components/Init.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheImage: typeof import('./src/components/TheImage.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
